version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/uploads:/app/uploads
  frontend:
    image: nginx:latest
    ports:
      - "5555:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
